- name: Ensure Redis is installed
  become: true
  apt:
    name: redis-server
    state: present

- name: Ensure Redis configuration
  become: true
  copy:
    src: files/redis.conf
    dest: /etc/redis/redis.conf
    owner: redis

- name: Ensure UFW allow reddis traffic
  become: true
  ufw:
    rule: allow
    port: '6379'
    insert: 0
    insert_relative_to: "first-ipv4"
    state: reloaded

- name: Ensure Redis is started
  become: true
  service:
    name: redis-server
    state: restarted
    enabled: true
