- name: Ensure Redis is installed
  become: true
  apt:
    name: redis-server
    state: present

- name: Ensure Redis configuration
  become: true
  copy:
    src: files/redis.conf
    dest: /etc/redis/redis.conf
    owner: redis

- name: Ensure UFW allow reddis traffic only on RFC1918 local networks
  become: true
  ufw:
    rule: allow
    port: '6379'
    insert: 0
    insert_relative_to: "first-ipv4"
    state: reloaded
    from: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

- name: Ensure Redis is started
  become: true
  service:
    name: redis-server
    state: restarted
    enabled: true
