- hosts: all
  roles:
        - base

- hosts: redis
  roles:
        - redis

- hosts: postgresql
  vars:
    postgresql_db: db
  roles:
        - postgresql

- hosts: poll
  vars:
    redis_host: redis
    poll_port: 80
  roles:
        - poll
