- name: Update/Upgrade distro
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe

- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - unzip
      - zsh
      - ufw

- name: Set timezone to Europe/Paris
  become: true
  community.general.timezone:
    name: Europe/Paris

- name: Initial setup of UFW
  become: true
  ufw:
    rule: allow
    name: OpenSSH

- name: Enable UFW
  become: true
  ufw:
    rule: reject
    state: disabled

